[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund"
  NEXT_TELEMETRY_DISABLED = "1"

# This is crucial - DO NOT skip processing for Next.js apps
[build.processing]
  skip_processing = false

# Important for static assets
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # Set this to false to ensure Next.js handles all routes
    fallback = false

# Cache Netlify build plugins
[[plugins]]
  package = "netlify-plugin-cache"
  [plugins.inputs]
    paths = [
      "node_modules/.cache",
      ".next/cache"
    ]
