[build]
  command = "npm run build"
  publish = ".next"
  ignore_warnings = true

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-audit --no-fund --no-strict-peer-deps"
  NEXT_TELEMETRY_DISABLED = "1"
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "1"
  PLAYWRIGHT_BROWSERS_PATH = "0"
  NEXT_IGNORE_ERRORS = "1"

# Essential: This tells Netlify NOT to process the Next.js assets
[build.processing]
  skip_processing = true

# Essential Next.js plugin to handle server-side rendering and API routes
[[plugins]]
  package = "@netlify/plugin-nextjs"
