version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret_password
      MYSQL_USER: node
      MYSQL_PASSWORD: secret_password
      MYSQL_DATABASE: myapp_dev
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--silent']
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        # Codespaces-compatible build arguments
        - NODE_VERSION=22
        - USERNAME=node
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
      - npm_cache:/home/node/.npm
      # Mount Docker socket for Docker-in-Docker functionality (if available)
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    command: sleep infinity
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3010:3010'
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_PREFIX=/home/node/.npm-global
      # Codespaces GitHub authentication (if available)
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
    # Ensure the node user exists and has proper UID/GID
    user: node
    # Improve Codespaces performance
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  node_modules: {}
  npm_cache: {}
  db_data: {}

# Codespaces networking
networks:
  default:
    name: y3dhub_network
