version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - node_modules:/workspace/node_modules
    working_dir: /workspace
    command: sleep infinity
    env_file:
      - ../.env
    depends_on:
      - db
    ports:
      - '3002:3002'
    user: '1000:1000' # Use numeric IDs instead of user:group names
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_PREFIX=/home/node/.npm-global
