import { execFile as execFileCb } from 'child_process'
import { randomBytes } from 'crypto'
import { promises as fs } from 'fs'
import path from 'path'
import { promisify } from 'util'

const execFile = promisify(execFileCb)

export interface OpenSCADRenderOptions {
    /** Variables to pass to OpenSCAD using -D name=value */
    variables?: Record<string, string | number>
    /** Directory to write the STL into (absolute or relative). Defaults to ./public/stl */
    outputDir?: string
    /** Custom file name (without path). If omitted, one is autogenerated */
    fileName?: string
}

/**
 * Renders a .scad file to an STL using the system‑installed `openscad` CLI.
 *
 * Example:
 * ```ts
 * const stl = await renderScadToStl('openscad/DualColour.scad', {
 *   variables: { line1: 'Hello', line2: 'World', line3: '' }
 * })
 * console.log('Created STL at', stl)
 * ```
 */
export async function renderScadToStl(
    scadPath: string,
    { variables = {}, outputDir = path.join(process.cwd(), 'public', 'stl'), fileName }: OpenSCADRenderOptions = {}
): Promise<string> {
    // Ensure source file exists
    await fs.access(scadPath)

    await fs.mkdir(outputDir, { recursive: true })

    const basename = path.basename(scadPath, path.extname(scadPath))
    const random = randomBytes(6).toString('hex')

    const finalName = fileName ?? `${basename}-${random}.stl`
    const outFile = path.join(outputDir, finalName)

    // Build argument list
    const args: string[] = []

    // Output path
    args.push('-o', outFile)

    // Variables via -D name=value
    Object.entries(variables).forEach(([key, value]) => {
        // Strings need quotes so OpenSCAD treats them as strings
        const formatted = typeof value === 'string' ? `\"${value}\"` : String(value)
        args.push('-D', `${key}=${formatted}`)
    })

    // Finally, the source .scad
    args.push(scadPath)

    try {
        await execFile('openscad', args, { maxBuffer: 1024 * 1024 * 10 })
    } catch (err) {
        const message = err instanceof Error ? err.message : String(err)
        throw new Error(`OpenSCAD failed to render STL: ${message}`)
    }

    return outFile
}

/**
 * Convenience wrapper around `renderScadToStl` for the provided DualColour.scad
 * file that ships with this repository.
 */
export async function renderDualColourTag(
    line1: string,
    line2 = '',
    line3 = '',
    options: Partial<Omit<OpenSCADRenderOptions, 'variables' | 'fileName'>> & { fileName?: string } = {}
) {
    const projectRoot = process.cwd()
    const scad = path.join(projectRoot, 'openscad', 'DualColour.scad')
    return renderScadToStl(scad, {
        ...options,
        variables: { line1, line2, line3 },
        fileName: options.fileName,
    })
}

// helper slug
export function slug(input: string) {
    // Keep original capitalization but remove unsafe filesystem characters.
    return input
        .replace(/\s+/g, '_')           // spaces → underscore
        .replace(/[^A-Za-z0-9_]/g, '')   // only alphanum & _
        .replace(/_+/g, '_')             // collapse repeats
        .slice(0, 60) || 'tag'
} 
